/**
 * WS9 Daemon — wire protocol types.
 *
 * Hand-typed counterpart to `packages/coding-agent/openapi.yaml`. The intent
 * is for these to be regenerated by `openapi-typescript-codegen` once we wire
 * codegen in CI — until then we hand-maintain. Keep them in sync.
 */

export type SessionState = "idle" | "running" | "stopped" | "error";

export type Role = "user" | "assistant" | "system" | "tool";

export interface SessionRecord {
	id: string;
	createdAt: string;
	updatedAt: string;
	state: SessionState;
	cwd: string;
	title?: string;
	model?: string;
	worker?: string;
}

export interface MessageRecord {
	id: string;
	sessionId: string;
	role: Role;
	text: string;
	createdAt: string;
}

export interface Transcript {
	sessionId: string;
	messages: MessageRecord[];
}

export interface CreateSessionRequest {
	cwd?: string;
	title?: string;
	model?: string;
	worker?: string;
}

export interface SendMessageRequest {
	text: string;
	worker?: string;
}

export interface Health {
	ok: true;
	version: string;
	uptimeSec: number;
}

export interface WorkerRecord {
	name: string;
	url: string;
	token?: string;
	registeredAt: string;
	lastSeenAt?: string;
	labels?: Record<string, string>;
}

export interface RegisterWorkerRequest {
	name: string;
	url: string;
	token?: string;
	labels?: Record<string, string>;
}

// ---- JSON-RPC 2.0 over WebSocket ----
//
// Notifications (server → client):
//   { jsonrpc: "2.0", method: "token", params: { sessionId, text, role } }
//   { jsonrpc: "2.0", method: "tool",  params: { sessionId, name, status } }
//   { jsonrpc: "2.0", method: "state", params: { sessionId, state } }
//   { jsonrpc: "2.0", method: "done",  params: { sessionId } }
//
// Requests (client → server):
//   { jsonrpc: "2.0", id: 1, method: "send",      params: { text } }
//   { jsonrpc: "2.0", id: 2, method: "interrupt", params: {} }

export type RpcId = string | number;

export interface RpcRequest<P = unknown> {
	jsonrpc: "2.0";
	id: RpcId;
	method: string;
	params?: P;
}

export interface RpcNotification<P = unknown> {
	jsonrpc: "2.0";
	method: string;
	params?: P;
}

export interface RpcResponse<R = unknown> {
	jsonrpc: "2.0";
	id: RpcId;
	result?: R;
	error?: { code: number; message: string; data?: unknown };
}

export type RpcEnvelope = RpcRequest | RpcNotification | RpcResponse;

export interface TokenParams {
	sessionId: string;
	text: string;
	role: Role;
}

export interface ToolParams {
	sessionId: string;
	name: string;
	status: "start" | "ok" | "err";
}

export interface StateParams {
	sessionId: string;
	state: SessionState;
}

export interface DoneParams {
	sessionId: string;
}

export interface SendParams {
	text: string;
}

export const DEFAULT_DAEMON_PORT = 7421;
export const DEFAULT_DAEMON_HOST = "127.0.0.1";

/** Minimum interval between coalesced token batches sent to clients. ~16 ms. */
export const TOKEN_TICK_MS = 16;
